name: Package JAR and Release on GitHub
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+[a-z]+'

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Package with Maven
        run: mvn --batch-mode --quiet package
      - name: Prepare staging
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
      - name: Renaming JAR file to convention
        run: 'mv staging/dungeonscli-1.jar staging/dungeonscli-${{ github.ref_name }}.jar'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          prerelease: false
          title: "DungeonsCLI ${{ github.ref_name }}"
          files: staging/*.jar